# Generated by Django 3.2.9 on 2022-02-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_jobs',
            name='applied_date',
            field=models.CharField(default='Hello', max_length=50),
        ),
    ]
