# Generated by Django 3.2.9 on 2022-02-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0006_alter_applied_jobs_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('full-time', 'Full-Time'), ('part-time', 'Part-Time')], default='full-time', max_length=50),
        ),
    ]
