# Generated by Django 3.2.9 on 2022-02-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0007_jobpost_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employermore',
            name='company_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
