# Generated by Django 3.2.9 on 2022-02-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0009_auto_20220212_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemore',
            name='upload_photo',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
