# Generated by Django 3.2.9 on 2022-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0010_candidatemore_upload_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemore',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
