# Generated by Django 3.2.9 on 2022-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0012_employermore_upload_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employermore',
            name='upload_photo',
            field=models.ImageField(blank=True, upload_to='profile1_image'),
        ),
    ]
