# Generated by Django 3.2.9 on 2022-03-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0013_alter_employermore_upload_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='q4',
            field=models.TextField(blank=True, max_length=250, verbose_name='How will you handle stressfull situation. Lets say deadline is near and teammates are not working properly?'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q5',
            field=models.TextField(blank=True, max_length=250, verbose_name='What all things do you consider when you have to be quick while making a decision?'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q6',
            field=models.TextField(blank=True, max_length=250, verbose_name='What are your short terms and long terms goals?'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q7',
            field=models.TextField(blank=True, max_length=250, verbose_name='Describe honesty in your own words.And tell me a situation where you chose to be honest instead of a lie'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q8',
            field=models.TextField(blank=True, max_length=200, verbose_name='When could you start?'),
        ),
    ]
