# Generated by Django 3.2.9 on 2022-03-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0014_auto_20220319_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='q8',
        ),
    ]
