# Generated by Django 3.2.9 on 2022-03-29 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0015_remove_questions_q8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField(max_length=500, verbose_name='How can we improve our system?')),
                ('q2', models.TextField(max_length=500, verbose_name='What difficulties have you faced while using the website?')),
                ('q3', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=250, verbose_name='how_would_rate_your_overall_experience_with_Job_Praise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
