# Generated by Django 3.2.9 on 2022-03-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0016_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_jobs',
            name='status',
            field=models.CharField(choices=[('in-touch', 'In-Touch'), ('Selected', 'selected'), ('Rejected', 'rejected')], default='Applied', max_length=50),
        ),
    ]
