# Generated by Django 3.2.9 on 2022-03-29 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0017_alter_applied_jobs_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('message_date', models.DateField(default=django.utils.timezone.now)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_proxy.employermore')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_proxy.candidatemore')),
            ],
        ),
    ]
