# Generated by Django 3.2.9 on 2022-03-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_proxy', '0020_alter_send_message_user_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='send_message',
        ),
    ]
